### ISSUE TITLE
Interest in Joining and Contributing to Spheron Network

### ISSUE THREAD

**Issue by Anandha-Vihari** [spheronFdn/awesome-spheron#1]
Dear Spheron Network Team,

I hope this message finds you well. My name is Anandha Vihari, and I am eager to contribute to the Spheron Network community. With a background in Artificial Intelligence and Machine Learning, as well as extensive experience in open-source development, I believe I can bring valuable skills and insights to your projects.

Could you please share the requirements or steps involved in joining your community? I am particularly interested in opportunities where I could leverage my expertise in AIML and open-source contributions.

Thank you for considering my request. I look forward to the possibility of collaborating with you.

Warm regards,
Anandha Vihari

**Comment by Anandha-Vihari** [comment]
@izrake i want to join in core team...

**Comment by rekpero** [comment]
sorry we don't have any opening right now...

**Comment by Anandha-Vihari** [comment]
@rekpero yeah i know,but i want to be involve in things that would change the world like Spheron Project...
